// <auto-generated />
using EF.Data.Access.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF.Data.Access.Migrations
{
    [DbContext(typeof(QuizDBContext))]
    partial class QuizDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EF.Data.Access.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TimeTaken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("EF.Data.Access.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = 2,
                            Option1 = "Hyper Trainer Marking Language",
                            Option2 = "Hyper Text Marketing Language",
                            Option3 = "Hyper Text Markup Language",
                            Option4 = "Hyper Text Markup Leveler",
                            QuestionText = "What does HTML stand for?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = 2,
                            Option1 = "ALU",
                            Option2 = "Memory",
                            Option3 = "CPU",
                            Option4 = "Control unit",
                            QuestionText = "The brain of any computer system is"
                        },
                        new
                        {
                            Id = 3,
                            Answer = 1,
                            Option1 = "FORTRAN",
                            Option2 = "PROLOG",
                            Option3 = "C",
                            Option4 = "COBOL",
                            QuestionText = "Which of the following computer language is used for artificial intelligence?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = 2,
                            Option1 = "Mathematical Mind",
                            Option2 = "Artistic mind",
                            Option3 = "Logical Mind",
                            Option4 = "Scientific Knowledge",
                            QuestionText = "What is the primary requisite of a good computer programmer?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = 2,
                            Image = "mouse.png",
                            Option1 = "Keyboard",
                            Option2 = "Monitor",
                            Option3 = "Mouse",
                            Option4 = "Graphics Card",
                            QuestionText = "Name the device."
                        },
                        new
                        {
                            Id = 6,
                            Answer = 0,
                            Option1 = "Analytical Engine",
                            Option2 = "Calculator",
                            Option3 = "Processor",
                            Option4 = "Abacus",
                            QuestionText = "The first mechanical computer designed by Charles Babbage was called"
                        },
                        new
                        {
                            Id = 7,
                            Answer = 1,
                            Option1 = "4 bits",
                            Option2 = "8 bits",
                            Option3 = "16 bits",
                            Option4 = "32 bits",
                            QuestionText = "One byte is equivalent to"
                        },
                        new
                        {
                            Id = 8,
                            Answer = 2,
                            Option1 = "FTP",
                            Option2 = "UML",
                            Option3 = "HTML",
                            Option4 = "URL",
                            QuestionText = "Web pages are written using"
                        },
                        new
                        {
                            Id = 9,
                            Answer = 3,
                            Option1 = "Dos",
                            Option2 = "Unix",
                            Option3 = "Window NT",
                            Option4 = "CSS",
                            QuestionText = "Which of the following is NOT operating system"
                        },
                        new
                        {
                            Id = 10,
                            Answer = 3,
                            Option1 = "Interface Program",
                            Option2 = "Interface Protocol",
                            Option3 = "Internet program",
                            Option4 = "Internet Protocol",
                            QuestionText = "What is the full form of IP"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
